Tue Aug  8 02:09:17 PM CDT 2023

diff --git a/.github/workflows/check-ci-connected.yml b/.github/workflows/check-ci-connected.yml
--- a/.github/workflows/check-ci-connected.yml
+++ b/.github/workflows/check-ci-connected.yml
@@ -18,4 +18,8 @@ jobs:
       run: |
         echo "The value of CI_CONNECTED is '${{ env.CI_CONNECTED }}'"
         test "${{ env.CI_CONNECTED }}" = "true" \
-          || { echo "CI is Disconnected. Set CI_CONNECTED to true in GitHub's repository environment variables" >&2; exit 1 ;}
+          || { \ 
+            echo "CI is Disconnected. Set CI_CONNECTED to true in GitHub's repository environment variables" >&2; \
+            echo "::error::CI is not enabled because the repositorie's CI_CONNECTED environment variable != true" \
+            exit 1
+          };
